The following standards will be assessed on the EDA quiz:

## FLOW

You should be able to:

- Define learning approaches (supervised vs. unsupervised learning) and learning tasks (regression, classification, and clustering).
- Interpret a dataset summary table.
- Describe a model’s goal and explain who might benefit from the model.
- Describe the five steps ML workflow and give a few examples of tasks for each step

## EDA-STAT

You should be able to:

- Understand and describe statistical measures, distributions, and tests
- Read and interpret charts, including identifying key features (skew, balance, shape) and chart types (histogram, boxplot, scatterplot)
- Identify different feature types (numeric, discrete, continuous, ordinal, categorical, binary, or none).
- Explain what factors to consider when deciding whether a feature type is appropriate to include in a machine learning model.

## Study Tips

Review the lecture slides, workbooks, homework assignments, and the associated lab.  
Quiz questions are similar (though not identical) to the types of questions covered in these materials.
You should be able to use appropriate terminology and apply the concepts covered in class to a variety of new scenarios.

The primary goal of each quiz is to give you an opportunity to apply concepts with clear and well-explained reasoning.  
Quizzes are also a valuable opportunity to receive feedback on your reasoning skills.  


