project:
  type: website
  output-dir: docs

website:
  title: "AI Literacy <br> in Education"

  search:
    type: textbox

  navbar:
    background: primary
    search: true

    left:
      - text: Bookclub
        menu: 
          - href: Bookclub/
            text: How to start the Bookclub
          - href: Bookclub/schedule.qmd 
            text: Schedule
          - href: Bookclub/discussion1.qmd
            text: Session 1
          - href: Bookclub/discussion2.qmd
            text: Session 2
          - href: Bookclub/discussion3.qmd
            text: Session 3 
          - href: Bookclub/stolaf_relections.qmd 
            text: Reflections from the St. Olaf community conversations 
      
      - text: Surveys
        menu: 
          - href: survey/
            text: How to use the surveys
          - href: survey/attitudes.qmd 
            text: Attitudes towards GenAI
          - href: survey/current_uses.qmd
            text: Current Uses of GenAI
          - href: survey/readiness.qmd
            text: Readiness to incorporate GenAI


      - href: about/resources.qmd
        text: Resources

      

    right:
      - text: About
        menu: 
        - href: about/people.qmd
          text: People
        - href: about/purpose.qmd
          text: How this came about
            
      - icon: github
        href: https://github.com/fortressokorie/ai_literacy

format:
  html:
    theme: yeti  #yeti #materia #lux #sandstone #spacelab #vapor   #litera #themes here: https://bootswatch.com/
    #css: styles.css
    toc: true

execute:
  freeze: auto

