The following standards will be assessed on the TREE quiz:

## ALG-TREE

You should be able to:

- Describe how the decision tree algorithm works 
- Define what the terms entropy, gini, uncertainty, decision boundary, region means in the context of this algorithm
- Draw and interpret the output of a decision tree and graph its associated regions

## TRAIN-TREE

You should be able to:

- Explain overfitting and underfitting in the context of this algorithm
- Interpret results from a decision tree model
- Give suggestions for improving the decision tree model

## Study Tips

Review the lecture slides, workbooks, homework assignments, and the associated lab.  
Quiz questions are similar (though not identical) to the types of questions covered in these materials.
You should be able to use appropriate terminology and apply the concepts covered in class to a variety of new scenarios.

The primary goal of each quiz is to give you an opportunity to apply concepts with clear and well-explained reasoning.  
Quizzes are also a valuable opportunity to receive feedback on your reasoning skills.  


## Formulas Given

Entropy: $-p*log_2(p) - (1-p)log_2(1-p)$ <br>
Gini impurity:   $2*p*(1-p)$ <br>

Impurity$_{\text{total}}:   2*P(target=yes)*P(target=no)$ <br>

Impurity$_{Question}:   P(\text{Q=yes})*\text{Impurity}(\text{Q=yes})*P(\text{Q=no})*\text{Impurity}(\text{Q=no})$




