The following standards will be assessed on the EVL quiz:

## EVAL

You should be able to:

- Identify which evaluation metrics to use for various ML tasks
- Compute metrics (formulas provided)
- Interpret metrics in an accessible way


## TRAIN

You should be able to:

- Know ways to separate train, validation, and test sets
- Define overfitting, underfitting, cross-fold validation
- Understand and give examples of the bias(underfitting) - variance (overfitting) tradeoff

## Study Tips

Review the lecture slides, workbooks, homework assignments, and the associated lab.  
Quiz questions are similar (though not identical) to the types of questions covered in these materials.
You should be able to use appropriate terminology and apply the concepts covered in class to a variety of new scenarios.

The primary goal of each quiz is to give you an opportunity to apply concepts with clear and well-explained reasoning.  
Quizzes are also a valuable opportunity to receive feedback on your reasoning skills.  


## Formulas given

$\text{Accuracy} = \frac{TP + TN}{TP + FP + FN + TN}$

$\text{Precision} = \frac{TP}{TP + FP}$

$\text{Recall} = \frac{TP}{TP + FN}$

$F1 = \frac{2 \cdot \text{Precision} \cdot \text{Recall}}{\text{Precision} + \text{Recall}}$

$MAE = \frac{1}{n} \sum |y_{obs} - y_{pred}|$

$MSE = \frac{1}{n} \sum (y_{obs} - y_{pred})^2$

$RMSE = \sqrt{MSE}$

